export { EmailGuardClient, EmailGuardApiError, emailguard } from "./client";
export type {
  Domain,
  DnsStatus,
  SpfResult,
  DkimResult,
  DmarcResult,
  BlacklistCheck,
  SurblCheck,
  SpamhausResponse,
  DmarcDomain,
  DmarcInsight,
  DmarcSource,
  DmarcFailure,
  SpfLookupResult,
  DkimLookupResult,
  DmarcLookupResult,
  InboxTest,
  InboxTestStatus,
  InboxTestProviderResult,
  SpamFilterTest,
  SpamCheckResult,
  SpamVerdict,
  ContactList,
  ContactVerificationStatus,
  ContactVerificationResult,
  HostLookupResult,
  EmailGuardListResponse,
  EmailGuardSingleResponse,
} from "./types";
