import { prisma } from "@/lib/db";
import { notify } from "@/lib/notify";
import { createInvoice } from "./operations";

/**
 * Format a Date as DD/MM/YYYY for line item description strings.
 */
function formatPeriod(date: Date): string {
  const dd = String(date.getDate()).padStart(2, "0");
  const mm = String(date.getMonth() + 1).padStart(2, "0");
  const yyyy = date.getFullYear();
  return `${dd}/${mm}/${yyyy}`;
}

/**
 * Subtract exactly 1 calendar month from a date.
 * Handles month-end edge cases: Mar 31 -> Feb 28 (or 29 in leap year).
 */
function subtractOneMonth(date: Date): Date {
  const prev = new Date(date);
  const originalDay = date.getDate();
  prev.setMonth(prev.getMonth() - 1);

  // If month underflow happened (e.g. Mar 31 -> Mar 3 due to Feb), roll back
  if (prev.getDate() !== originalDay) {
    prev.setDate(0); // Sets to last day of previous month
  }

  return prev;
}

/**
 * Auto-generate draft invoices for workspaces with a billing renewal date
 * falling within the next 7 days.
 *
 * Idempotent: skips creation if a draft or sent invoice already exists
 * for the same workspace + renewalDate combination.
 *
 * @returns Object with counts of created and skipped invoices.
 */
export async function generateDueInvoices(): Promise<{
  created: number;
  skipped: number;
}> {
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  const windowEnd = new Date(today);
  windowEnd.setDate(windowEnd.getDate() + 7);
  windowEnd.setHours(23, 59, 59, 999);

  // Find workspaces with a renewal date in the next 7 days and billing amounts configured
  const workspaces = await prisma.workspace.findMany({
    where: {
      billingRenewalDate: {
        gte: today,
        lte: windowEnd,
      },
      OR: [
        { billingRetainerPence: { gt: 0 } },
        { billingPlatformFeePence: { gt: 0 } },
      ],
    },
  });

  let created = 0;
  let skipped = 0;

  for (const ws of workspaces) {
    if (!ws.billingRenewalDate) continue;

    // Idempotency check: skip if draft or sent invoice already exists for this renewal
    const existing = await prisma.invoice.findFirst({
      where: {
        workspaceSlug: ws.slug,
        renewalDate: ws.billingRenewalDate,
        status: { in: ["draft", "sent"] },
      },
    });

    if (existing) {
      skipped++;
      continue;
    }

    const billingPeriodEnd = ws.billingRenewalDate;
    const billingPeriodStart = subtractOneMonth(billingPeriodEnd);

    // Build line items from workspace billing config
    const lineItems: { description: string; quantity: number; unitPricePence: number }[] = [];

    if (ws.billingRetainerPence && ws.billingRetainerPence > 0) {
      lineItems.push({
        description: `Cold Outbound Retainer (${formatPeriod(billingPeriodStart)} - ${formatPeriod(billingPeriodEnd)})`,
        quantity: 1,
        unitPricePence: ws.billingRetainerPence,
      });
    }

    if (ws.billingPlatformFeePence && ws.billingPlatformFeePence > 0) {
      lineItems.push({
        description: `Cold Outbound Platform Fee (${formatPeriod(billingPeriodStart)} - ${formatPeriod(billingPeriodEnd)})`,
        quantity: 1,
        unitPricePence: ws.billingPlatformFeePence,
      });
    }

    if (lineItems.length === 0) {
      skipped++;
      continue;
    }

    try {
      await createInvoice({
        workspaceSlug: ws.slug,
        lineItems,
        billingPeriodStart,
        billingPeriodEnd,
        renewalDate: ws.billingRenewalDate,
        autoGenerated: true,
      });

      // Advance billingRenewalDate by 1 month so future invoices keep generating
      const nextRenewal = new Date(ws.billingRenewalDate);
      const originalDay = ws.billingRenewalDate.getDate();
      nextRenewal.setMonth(nextRenewal.getMonth() + 1);
      // Handle month-end edge cases (e.g. Jan 31 -> Feb 28)
      if (nextRenewal.getDate() !== originalDay) {
        nextRenewal.setDate(0); // Roll back to last day of previous month
      }

      await prisma.workspace.update({
        where: { slug: ws.slug },
        data: { billingRenewalDate: nextRenewal },
      });

      created++;
    } catch (err) {
      console.error(`[invoice-generator] Failed to create invoice for ${ws.slug}:`, err);
      skipped++;
    }
  }

  return { created, skipped };
}

/**
 * Detect draft invoices that have been sitting unreviewed for more than 3 days.
 * Sends a warning notification for each stale draft so they don't pile up.
 *
 * @returns Count of stale draft alerts sent.
 */
export async function alertStaleDraftInvoices(): Promise<number> {
  const threeDaysAgo = new Date();
  threeDaysAgo.setDate(threeDaysAgo.getDate() - 3);

  const staleDrafts = await prisma.invoice.findMany({
    where: {
      status: "draft",
      createdAt: { lt: threeDaysAgo },
    },
  });

  if (staleDrafts.length === 0) return 0;

  let alertCount = 0;

  for (const invoice of staleDrafts) {
    const ageMs = Date.now() - invoice.createdAt.getTime();
    const ageDays = Math.round(ageMs / (24 * 60 * 60 * 1000));

    try {
      await notify({
        type: "stale_draft_alert",
        severity: "warning",
        title: `Stale draft invoice: ${invoice.invoiceNumber}`,
        message: `${invoice.clientCompanyName} (${invoice.workspaceSlug}) — draft invoice has been unreviewed for ${ageDays} days. Review and send or discard.`,
        workspaceSlug: invoice.workspaceSlug,
        metadata: {
          invoiceId: invoice.id,
          invoiceNumber: invoice.invoiceNumber,
          totalPence: invoice.totalPence,
          ageDays,
          createdAt: invoice.createdAt.toISOString(),
        },
      });
      alertCount++;
    } catch (err) {
      console.error(`[invoice-generator] Failed to send stale draft alert for ${invoice.invoiceNumber}:`, err);
    }
  }

  return alertCount;
}

/**
 * Alert admin via Slack when an unpaid invoice's workspace has a renewal date
 * within the next 48 hours.
 *
 * Targets the OPS_SLACK_CHANNEL_ID (admin ops channel, not workspace channel).
 *
 * @returns Count of alerts sent.
 */
export async function alertUnpaidBeforeRenewal(): Promise<number> {
  const now = new Date();
  const in48h = new Date(now.getTime() + 48 * 60 * 60 * 1000);

  // Find workspaces with a renewal date within the next 48 hours
  const workspaces = await prisma.workspace.findMany({
    where: {
      billingRenewalDate: {
        gte: now,
        lte: in48h,
      },
    },
  });

  if (workspaces.length === 0) return 0;

  const workspaceSlugs = workspaces.map((ws) => ws.slug);

  // Find unpaid invoices for these workspaces
  const unpaidInvoices = await prisma.invoice.findMany({
    where: {
      workspaceSlug: { in: workspaceSlugs },
      status: { in: ["sent", "overdue"] },
    },
  });

  if (unpaidInvoices.length === 0) return 0;

  // Build a lookup map for workspace by slug
  const workspaceMap = new Map(workspaces.map((ws) => [ws.slug, ws]));

  let alertCount = 0;

  for (const invoice of unpaidInvoices) {
    const ws = workspaceMap.get(invoice.workspaceSlug);
    if (!ws?.billingRenewalDate) continue;

    const renewalMs = ws.billingRenewalDate.getTime() - now.getTime();
    const hoursUntilRenewal = Math.round(renewalMs / (60 * 60 * 1000));

    try {
      await notify({
        type: "unpaid_renewal_alert",
        severity: "warning",
        title: `Unpaid invoice before renewal: ${invoice.invoiceNumber}`,
        message: `${ws.name} — invoice ${invoice.invoiceNumber} is unpaid. Renewal in ${hoursUntilRenewal}h.`,
        workspaceSlug: ws.slug,
        metadata: {
          invoiceId: invoice.id,
          invoiceNumber: invoice.invoiceNumber,
          status: invoice.status,
          hoursUntilRenewal,
          renewalDate: ws.billingRenewalDate.toISOString(),
        },
      });
      alertCount++;
    } catch (err) {
      console.error(`[invoice-generator] Failed to send 48h alert for ${invoice.invoiceNumber}:`, err);
    }
  }

  return alertCount;
}
