import { prisma } from "@/lib/db";
import { getNextInvoiceNumber } from "./numbering";
import {
  CreateInvoiceInput,
  InvoiceStatus,
  InvoiceWithLineItems,
  VALID_TRANSITIONS,
} from "./types";

/**
 * Advance a renewal date by exactly 1 calendar month.
 * Handles month-end edge cases: Jan 31 -> Feb 28 (or 29 in leap year).
 */
export function advanceRenewalDate(date: Date): Date {
  const next = new Date(date);
  const originalDay = date.getDate();
  next.setMonth(next.getMonth() + 1);

  // If month overflow happened (e.g. Jan 31 -> Mar 2), roll back to last day of previous month
  if (next.getDate() !== originalDay) {
    next.setDate(0); // Sets to last day of previous month
  }

  return next;
}

/**
 * Create a new invoice for a workspace.
 * Snapshots sender + client details, computes totals, assigns invoice number.
 */
export async function createInvoice(
  input: CreateInvoiceInput
): Promise<InvoiceWithLineItems> {
  const {
    workspaceSlug,
    lineItems,
    billingPeriodStart,
    billingPeriodEnd,
    issueDate = new Date(),
    renewalDate,
    autoGenerated = false,
  } = input;

  // Fetch workspace for billing fields
  const workspace = await prisma.workspace.findUnique({
    where: { slug: workspaceSlug },
  });

  if (!workspace) {
    throw new Error(`Workspace not found: ${workspaceSlug}`);
  }

  if (!workspace.invoicePrefix) {
    throw new Error(
      `Workspace ${workspaceSlug} has no invoicePrefix configured`
    );
  }

  if (!workspace.billingCompanyName) {
    throw new Error(
      `Workspace ${workspaceSlug} has no billingCompanyName configured`
    );
  }

  // Fetch global sender settings (only one record)
  const senderSettings = await prisma.invoiceSenderSettings.findFirst();

  if (!senderSettings) {
    throw new Error(
      "No InvoiceSenderSettings found — configure sender details in admin settings"
    );
  }

  // Generate atomic invoice number
  const invoiceNumber = await getNextInvoiceNumber(
    workspaceSlug,
    workspace.invoicePrefix
  );

  // Compute line item amounts and totals (all integer pence)
  const lineItemsWithAmounts = lineItems.map((item) => ({
    description: item.description,
    quantity: item.quantity,
    unitPricePence: item.unitPricePence,
    amountPence: item.quantity * item.unitPricePence,
  }));

  const subtotalPence = lineItemsWithAmounts.reduce(
    (sum, item) => sum + item.amountPence,
    0
  );

  const taxRate = workspace.invoiceTaxRate ?? 0;
  const taxAmountPence = Math.round((subtotalPence * taxRate) / 100);
  const totalPence = subtotalPence + taxAmountPence;

  // Compute due date
  const paymentTermsDays = workspace.billingPaymentTermsDays ?? 5;
  const dueDate = new Date(issueDate);
  dueDate.setDate(dueDate.getDate() + paymentTermsDays);

  // Build bank details string for snapshot
  const bankDetails =
    senderSettings.accountNumber || senderSettings.sortCode
      ? [
          senderSettings.accountNumber
            ? `Account Number: ${senderSettings.accountNumber}`
            : null,
          senderSettings.sortCode
            ? `Sort Code: ${senderSettings.sortCode}`
            : null,
        ]
          .filter(Boolean)
          .join("\n")
      : null;

  // Build client address snapshot
  const clientAddressParts = [
    workspace.billingAddressLine1,
    workspace.billingAddressLine2,
    workspace.billingCity,
    workspace.billingPostcode,
  ].filter(Boolean);
  const clientAddress =
    clientAddressParts.length > 0 ? clientAddressParts.join("\n") : null;

  // Generate portal view token
  const viewToken = crypto.randomUUID();

  // Create invoice with nested line items
  const invoice = await prisma.invoice.create({
    data: {
      invoiceNumber,
      workspaceSlug,
      senderName: senderSettings.senderName,
      senderAddress: senderSettings.senderAddress ?? null,
      senderEmail: senderSettings.senderEmail,
      bankDetails,
      clientCompanyName: workspace.billingCompanyName,
      clientAddress,
      issueDate,
      dueDate,
      billingPeriodStart: billingPeriodStart ?? null,
      billingPeriodEnd: billingPeriodEnd ?? null,
      subtotalPence,
      taxRate,
      taxAmountPence,
      totalPence,
      status: "draft",
      autoGenerated,
      renewalDate: renewalDate ?? null,
      viewToken,
      lineItems: {
        create: lineItemsWithAmounts,
      },
    },
    include: { lineItems: true },
  });

  return invoice as InvoiceWithLineItems;
}

/**
 * Get a single invoice by ID, including line items.
 */
export async function getInvoice(
  id: string
): Promise<InvoiceWithLineItems | null> {
  const invoice = await prisma.invoice.findUnique({
    where: { id },
    include: { lineItems: true },
  });
  return invoice as InvoiceWithLineItems | null;
}

/**
 * Get an invoice by its portal view token, including line items.
 */
export async function getInvoiceByToken(
  token: string
): Promise<InvoiceWithLineItems | null> {
  const invoice = await prisma.invoice.findUnique({
    where: { viewToken: token },
    include: { lineItems: true },
  });
  return invoice as InvoiceWithLineItems | null;
}

/**
 * List invoices with optional filters, ordered by issue date descending.
 */
export async function listInvoices(filters?: {
  workspaceSlug?: string;
  status?: string;
}): Promise<InvoiceWithLineItems[]> {
  const invoices = await prisma.invoice.findMany({
    where: {
      ...(filters?.workspaceSlug
        ? { workspaceSlug: filters.workspaceSlug }
        : {}),
      ...(filters?.status ? { status: filters.status } : {}),
    },
    include: { lineItems: true },
    orderBy: { issueDate: "desc" },
  });
  return invoices as InvoiceWithLineItems[];
}

/**
 * Update invoice status with transition validation.
 * Sets sentAt/paidAt timestamps automatically.
 * When marking as "paid", advances the workspace billingRenewalDate by 1 month.
 */
export async function updateInvoiceStatus(
  id: string,
  newStatus: InvoiceStatus
): Promise<InvoiceWithLineItems> {
  const invoice = await prisma.invoice.findUnique({
    where: { id },
    include: { lineItems: true },
  });

  if (!invoice) {
    throw new Error(`Invoice not found: ${id}`);
  }

  const currentStatus = invoice.status;
  const validNextStatuses = VALID_TRANSITIONS[currentStatus] ?? [];

  if (!validNextStatuses.includes(newStatus)) {
    throw new Error(
      `Invalid status transition: ${currentStatus} -> ${newStatus}. Valid transitions: ${validNextStatuses.join(", ") || "none"}`
    );
  }

  const now = new Date();
  const updateData: Record<string, unknown> = { status: newStatus };

  if (newStatus === "sent") {
    updateData.sentAt = now;
  } else if (newStatus === "paid") {
    updateData.paidAt = now;
  }

  return prisma.$transaction(async (tx) => {
    const updated = await tx.invoice.update({
      where: { id },
      data: updateData,
      include: { lineItems: true },
    });

    // When paid, advance workspace billingRenewalDate by 1 calendar month
    if (newStatus === "paid") {
      const workspace = await tx.workspace.findUnique({
        where: { slug: invoice.workspaceSlug },
      });

      if (workspace?.billingRenewalDate) {
        const expectedRenewalDate =
          invoice.renewalDate ?? workspace.billingRenewalDate;
        const nextRenewalDate = advanceRenewalDate(expectedRenewalDate);
        const renewalAdvance = await tx.workspace.updateMany({
          where: {
            slug: invoice.workspaceSlug,
            billingRenewalDate: expectedRenewalDate,
          },
          data: { billingRenewalDate: nextRenewalDate },
        });
        if (renewalAdvance.count === 0) {
          throw new Error(
            `Workspace ${invoice.workspaceSlug} billing renewal date changed concurrently during payment finalization`,
          );
        }
      }
    }

    return updated as InvoiceWithLineItems;
  });
}
