export type InvoiceStatus = "draft" | "sent" | "paid" | "overdue";

// Prisma Invoice with lineItems included
export type InvoiceWithLineItems = {
  id: string;
  invoiceNumber: string;
  workspaceSlug: string;
  senderName: string;
  senderAddress: string | null;
  senderEmail: string;
  bankDetails: string | null;
  clientCompanyName: string;
  clientAddress: string | null;
  issueDate: Date;
  dueDate: Date;
  billingPeriodStart: Date | null;
  billingPeriodEnd: Date | null;
  subtotalPence: number;
  taxRate: number;
  taxAmountPence: number;
  totalPence: number;
  status: string;
  sentAt: Date | null;
  paidAt: Date | null;
  autoGenerated: boolean;
  renewalDate: Date | null;
  viewToken: string | null;
  reminderSentAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  lineItems: {
    id: string;
    invoiceId: string;
    description: string;
    quantity: number;
    unitPricePence: number;
    amountPence: number;
  }[];
};

export interface CreateInvoiceInput {
  workspaceSlug: string;
  lineItems: { description: string; quantity: number; unitPricePence: number }[];
  billingPeriodStart?: Date;
  billingPeriodEnd?: Date;
  issueDate?: Date; // defaults to today
  renewalDate?: Date; // set for auto-generated invoices
  autoGenerated?: boolean;
}

export interface InvoiceSenderSettingsData {
  senderName: string;
  senderAddress?: string | null;
  senderEmail: string;
  accountNumber?: string | null;
  sortCode?: string | null;
}

// Valid status transitions
export const VALID_TRANSITIONS: Record<string, string[]> = {
  draft: ["sent"],
  sent: ["paid", "overdue"],
  overdue: ["paid"],
  paid: [],
};
