import { tool } from "ai";
import { z } from "zod";
import { readFile, access } from "fs/promises";
import { constants } from "fs";
import { join } from "path";
import { prisma } from "@/lib/db";
import { getWorkspaceDetails, getClientForWorkspace } from "@/lib/workspaces";
import { runAgent } from "./runner";
import { NOVA_MODEL } from "./types";
import type {
  AgentConfig,
  IntelligenceInput,
  IntelligenceOutput,
} from "./types";
import { sanitizePromptInput, USER_INPUT_GUARD } from "./utils";
import { loadRules } from "./load-rules";
import { appendToMemory, appendToGlobalMemory } from "./memory";

// --- Intelligence Agent Tools ---

const intelligenceTools = {
  cachedMetrics: tool({
    description:
      "Get cached performance metrics for a workspace: reply rates, open rates, bounce rates by campaign.",
    inputSchema: z.object({
      workspaceSlug: z.string().describe("The workspace slug"),
    }),
    execute: async ({ workspaceSlug }) => {
      const metrics = await prisma.cachedMetrics.findMany({
        where: { workspace: workspaceSlug },
        orderBy: { computedAt: "desc" },
      });
      return metrics.map((m) => ({
        metricType: m.metricType,
        metricKey: m.metricKey,
        date: m.date,
        data: JSON.parse(m.data),
        computedAt: m.computedAt,
      }));
    },
  }),

  insightList: tool({
    description:
      "Get generated insights stored in the database for a workspace. These are auto-generated by Trigger.dev cron — this tool reads them, it does not create new ones.",
    inputSchema: z.object({
      workspaceSlug: z.string().describe("The workspace slug"),
    }),
    execute: async ({ workspaceSlug }) => {
      const insights = await prisma.insight.findMany({
        where: { workspaceSlug },
        orderBy: { createdAt: "desc" },
        take: 50,
        select: {
          id: true,
          category: true,
          observation: true,
          evidence: true,
          confidence: true,
          priority: true,
          actionType: true,
          actionDescription: true,
          status: true,
          createdAt: true,
        },
      });
      return insights.map((i) => ({
        ...i,
        evidence: JSON.parse(i.evidence),
      }));
    },
  }),

  workspaceIntelligence: tool({
    description:
      "Get full workspace details including ICP, value props, package tier, vertical, and website analysis data.",
    inputSchema: z.object({
      workspaceSlug: z.string().describe("The workspace slug"),
    }),
    execute: async ({ workspaceSlug }) => {
      const ws = await getWorkspaceDetails(workspaceSlug);
      if (!ws) return { error: `Workspace '${workspaceSlug}' not found` };
      return {
        name: ws.name,
        slug: ws.slug,
        vertical: ws.vertical,
        website: ws.website,
        icpCountries: ws.icpCountries,
        icpIndustries: ws.icpIndustries,
        icpCompanySize: ws.icpCompanySize,
        icpDecisionMakerTitles: ws.icpDecisionMakerTitles,
        coreOffers: ws.coreOffers,
        differentiators: ws.differentiators,
        painPoints: ws.painPoints,
        package: ws.package,
        status: ws.status,
      };
    },
  }),

  campaignsGet: tool({
    description:
      "Get EmailBison campaign data for a workspace. Returns campaign names, statuses, and stats.",
    inputSchema: z.object({
      workspaceSlug: z.string().describe("The workspace slug"),
    }),
    execute: async ({ workspaceSlug }) => {
      try {
        const client = await getClientForWorkspace(workspaceSlug);
        const campaigns = await client.getCampaigns();
        return campaigns;
      } catch (err) {
        return {
          error: `Failed to get campaigns: ${err instanceof Error ? err.message : String(err)}`,
        };
      }
    },
  }),

  readGlobalInsights: tool({
    description:
      "Read the cross-client global insights file. Contains patterns and benchmarks across all workspaces.",
    inputSchema: z.object({}),
    execute: async () => {
      const projectRoot = process.env.PROJECT_ROOT ?? process.cwd();
      const filePath = join(
        projectRoot,
        ".nova",
        "memory",
        "global-insights.md",
      );

      try {
        await access(filePath, constants.F_OK);
        const content = await readFile(filePath, "utf8");
        return content.trim() || "No global insights yet";
      } catch {
        return "No global insights yet";
      }
    },
  }),
};

// --- Agent Configuration ---

const INTELLIGENCE_SYSTEM_PROMPT = `You are the Outsignal Intelligence Agent — a data-driven analyst specializing in campaign performance analysis, cross-client benchmarks, and actionable optimization insights.

${loadRules("intelligence-rules.md")}`;

const intelligenceConfig: AgentConfig = {
  name: "intelligence",
  model: NOVA_MODEL,
  systemPrompt: INTELLIGENCE_SYSTEM_PROMPT + USER_INPUT_GUARD,
  tools: intelligenceTools,
  maxSteps: 10,
  onComplete: async (result, options) => {
    const slug = options?.workspaceSlug;
    if (!slug) return;

    // Extract summary for workspace-specific learnings
    const firstLine =
      result.text?.split("\n").find((l) => l.trim().length > 0) ?? "";
    const summary =
      firstLine.slice(0, 150) || "Performance analysis completed";

    await appendToMemory(slug, "learnings.md", `analytics: ${summary}`);

    // Write to global insights if cross-client patterns detected
    const text = result.text ?? "";
    const mentionsMultiple =
      text.includes("benchmark") ||
      text.includes("cross-client") ||
      text.includes("across workspaces") ||
      text.includes("industry average");

    if (mentionsMultiple) {
      await appendToGlobalMemory(summary);
    }
  },
};

// --- Public API ---

/**
 * Run the Intelligence Agent to analyze campaign performance and surface insights.
 *
 * Can be called from:
 * - CLI scripts
 * - Dashboard chat via orchestrator delegation
 * - Weekly intelligence cron
 */
export async function runIntelligenceAgent(
  input: IntelligenceInput,
): Promise<IntelligenceOutput> {
  const userMessage = buildIntelligenceMessage(input);

  const result = await runAgent<IntelligenceOutput>(
    intelligenceConfig,
    userMessage,
    {
      triggeredBy: "orchestrator",
      workspaceSlug: input.workspaceSlug,
    },
  );

  return (
    result.output ?? {
      action: "analysis",
      summary: result.text,
    }
  );
}

function buildIntelligenceMessage(input: IntelligenceInput): string {
  const parts: string[] = [];
  parts.push(`Workspace: ${input.workspaceSlug}`);
  parts.push("", `Task: ${sanitizePromptInput(input.task)}`);
  return parts.join("\n");
}

export { intelligenceConfig, intelligenceTools };
