const { PrismaClient } = require('@prisma/client');
const crypto = require('crypto');

async function main() {
  const prisma = new PrismaClient();

  try {
    // 1. Fetch sender settings
    const sender = await prisma.invoiceSenderSettings.findFirst();
    if (!sender) throw new Error('No InvoiceSenderSettings found');
    console.log('Sender:', JSON.stringify(sender, null, 2));

    // 2. Get workspace
    const workspace = await prisma.workspace.findUnique({ where: { slug: 'lime-recruitment' } });
    if (!workspace) throw new Error('Workspace lime-recruitment not found');

    // 3. Create invoice with line items
    const invoice = await prisma.invoice.create({
      data: {
        invoiceNumber: 'PS04',
        workspaceSlug: 'lime-recruitment',
        senderName: sender.senderName,
        senderAddress: sender.senderAddress,
        senderEmail: sender.senderEmail,
        bankDetails: 'Account: 20963400, Sort Code: 60-83-71',
        clientCompanyName: 'Paytier Solutions Ltd',
        clientAddress: 'Arkwright House, Parsonage Gardens, Manchester, M3 2LF',
        issueDate: new Date('2026-02-23'),
        dueDate: new Date('2026-02-28'),
        billingPeriodStart: new Date('2026-02-23'),
        billingPeriodEnd: new Date('2026-03-26'),
        subtotalPence: 113000,
        taxRate: 0,
        taxAmountPence: 0,
        totalPence: 113000,
        status: 'draft',
        autoGenerated: false,
        renewalDate: new Date('2026-03-26'),
        viewToken: crypto.randomUUID(),
        lineItems: {
          create: [
            {
              description: 'Cold Outbound Retainer (23/02/2026 - 26/03/2026)',
              quantity: 1,
              unitPricePence: 75000,
              amountPence: 75000,
            },
            {
              description: 'Cold Outbound Platform Fee (23/02/2026 - 26/03/2026)',
              quantity: 1,
              unitPricePence: 38000,
              amountPence: 38000,
            },
          ],
        },
      },
      include: { lineItems: true },
    });

    console.log('\nCreated invoice:', JSON.stringify(invoice, null, 2));

    // 4. Update invoice sequence
    const seq = await prisma.invoiceSequence.updateMany({
      where: { workspaceSlug: 'lime-recruitment' },
      data: { lastNumber: 4 },
    });
    console.log('\nUpdated InvoiceSequence rows:', seq.count);

  } finally {
    await prisma.$disconnect();
  }
}

main().catch(e => { console.error(e); process.exit(1); });
