/**
 * Nova Memory CLI — Seed per-workspace memory directories for Nova CLI skills.
 *
 * Usage:
 *   npx tsx scripts/nova-memory.ts seed {slug}    — seed one workspace
 *   npx tsx scripts/nova-memory.ts seed --all     — seed all workspaces from DB
 *
 * Memory files created per workspace:
 *   .nova/memory/{slug}/profile.md     — always overwritten (fresh from DB)
 *   .nova/memory/{slug}/campaigns.md   — skipped if exists (append-only)
 *   .nova/memory/{slug}/feedback.md    — skipped if exists (append-only)
 *   .nova/memory/{slug}/learnings.md   — skipped if exists (append-only)
 *
 * Global:
 *   .nova/memory/global-insights.md    — always overwritten (cross-client averages)
 */

import { config } from "dotenv";
config({ path: ".env.local" });

import { mkdir, writeFile, access } from "fs/promises";
import { constants } from "fs";
import { join } from "path";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();
const MEMORY_ROOT = ".nova/memory";

// ---- Helpers ----------------------------------------------------------------

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

function isoDate(): string {
  return new Date().toISOString().split("T")[0];
}

function or(value: string | null | undefined, fallback: string): string {
  if (!value || value.trim() === "") return fallback;
  return value.trim();
}

function parseJsonArray(raw: string | null | undefined): string[] {
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

// ---- profile.md -------------------------------------------------------------

async function writeProfile(slug: string, dirPath: string): Promise<void> {
  const workspace = await prisma.workspace.findUnique({
    where: { slug },
    select: {
      slug: true,
      name: true,
      vertical: true,
      website: true,
      package: true,
      icpCriteriaPrompt: true,
      icpCountries: true,
      icpIndustries: true,
      icpCompanySize: true,
      icpDecisionMakerTitles: true,
      coreOffers: true,
      painPoints: true,
      differentiators: true,
      normalizationPrompt: true,
      outreachTonePrompt: true,
      enabledModules: true,
      monthlyCampaignAllowance: true,
      monthlyLeadQuota: true,
      senderFullName: true,
      senderJobTitle: true,
      onboardingNotes: true,
    },
  });

  if (!workspace) {
    throw new Error(`Workspace '${slug}' not found in database`);
  }

  const enabledModules = parseJsonArray(workspace.enabledModules);
  const channels = enabledModules.length > 0 ? enabledModules.join(", ") : "email";

  const icpSection = [
    workspace.icpCriteriaPrompt
      ? `**ICP Description:** ${workspace.icpCriteriaPrompt}`
      : `**ICP Description:** Not configured`,
    workspace.icpIndustries
      ? `**Industries:** ${workspace.icpIndustries}`
      : `**Industries:** Not configured`,
    workspace.icpCountries
      ? `**Countries:** ${workspace.icpCountries}`
      : `**Countries:** Not configured`,
    workspace.icpCompanySize
      ? `**Company Size:** ${workspace.icpCompanySize}`
      : `**Company Size:** Not configured`,
    workspace.icpDecisionMakerTitles
      ? `**Decision Maker Titles:** ${workspace.icpDecisionMakerTitles}`
      : `**Decision Maker Titles:** Not configured`,
  ].join("\n");

  const content = `<!-- profile.md | workspace: ${slug} | seeded: ${isoDate()} | re-seed: overwrites this file -->
<!-- Write governance: NEVER append to this file — it is regenerated by nova-memory seed -->

# ${workspace.name} — Workspace Profile

## Company

| Field | Value |
|-------|-------|
| Name | ${or(workspace.name, "Not set")} |
| Vertical | ${or(workspace.vertical, "Not configured")} |
| Website | ${or(workspace.website, "Not configured")} |
| Package | ${workspace.package} |
| Enabled Channels | ${channels} |
| Monthly Campaign Allowance | ${workspace.monthlyCampaignAllowance} |
| Monthly Lead Quota | ${workspace.monthlyLeadQuota} |

## ICP

${icpSection}

${workspace.coreOffers ? `**Core Offers:**\n${workspace.coreOffers}` : "**Core Offers:** Not configured"}

${workspace.painPoints ? `**Pain Points:**\n${workspace.painPoints}` : "**Pain Points:** Not configured"}

${workspace.differentiators ? `**Differentiators:**\n${workspace.differentiators}` : "**Differentiators:** Not configured"}

## Tone & Voice

${workspace.outreachTonePrompt ? workspace.outreachTonePrompt : "Not configured — use professional but friendly tone by default"}

${workspace.normalizationPrompt ? `**Normalization Rules:**\n${workspace.normalizationPrompt}` : ""}

## Outreach Channels

Active: ${channels}

## Key Contacts

| Field | Value |
|-------|-------|
| Sender Name | ${or(workspace.senderFullName, "Not configured")} |
| Sender Title | ${or(workspace.senderJobTitle, "Not configured")} |

## Onboarding Notes

${or(workspace.onboardingNotes, "None recorded")}

## Standing Instructions

<!-- Admin-editable section. Examples: "Rise prefers short sequences", "Never use hyphens in copy", "Covenco wants formal tone only" -->
<!-- Agents: read this section before every task. These instructions override defaults. -->

(No standing instructions configured yet — admin can edit this file directly to add client-specific rules)
`;

  await writeFile(join(dirPath, "profile.md"), content, "utf8");
}

// ---- campaigns.md -----------------------------------------------------------

async function writeCampaigns(slug: string, dirPath: string): Promise<{ created: boolean }> {
  const filePath = join(dirPath, "campaigns.md");
  if (await fileExists(filePath)) {
    return { created: false };
  }

  const campaigns = await prisma.campaign.findMany({
    where: { workspaceSlug: slug },
    orderBy: { createdAt: "desc" },
    select: {
      id: true,
      name: true,
      channels: true,
      status: true,
      createdAt: true,
    },
  });

  const campaignIds = campaigns.map((c) => c.id);

  let metricsMap: Record<string, { replyRate?: number; openRate?: number; bounceRate?: number; totalLeadsContacted?: number }> = {};

  if (campaignIds.length > 0) {
    const snapshots = await prisma.cachedMetrics.findMany({
      where: {
        metricType: "campaign_snapshot",
        metricKey: { in: campaignIds },
      },
      select: {
        metricKey: true,
        data: true,
      },
    });

    for (const snapshot of snapshots) {
      try {
        const parsed = JSON.parse(snapshot.data as string);
        metricsMap[snapshot.metricKey] = {
          replyRate: parsed.replyRate,
          openRate: parsed.openRate,
          bounceRate: parsed.bounceRate,
          totalLeadsContacted: parsed.totalLeadsContacted,
        };
      } catch {
        // skip malformed snapshot
      }
    }
  }

  const rows = campaigns.map((c) => {
    const channels = parseJsonArray(c.channels).join(", ") || "email";
    const m = metricsMap[c.id] || {};
    const replyRate = m.replyRate != null ? `${(m.replyRate * 100).toFixed(1)}%` : "—";
    const openRate = m.openRate != null ? `${(m.openRate * 100).toFixed(1)}%` : "—";
    const leads = m.totalLeadsContacted != null ? String(m.totalLeadsContacted) : "—";
    return `| ${c.name} | ${channels} | ${c.status} | ${replyRate} | ${openRate} | ${leads} |`;
  });

  const tableSection = campaigns.length > 0
    ? `| Campaign | Channel | Status | Reply Rate | Open Rate | Leads |
|----------|---------|--------|------------|-----------|-------|
${rows.join("\n")}`
    : "_No campaigns recorded yet._";

  const content = `<!-- campaigns.md | workspace: ${slug} | seeded: ${isoDate()} | re-seed: skips if exists -->
<!-- Write governance: APPEND only, with ISO timestamp. Max 200 lines. Never delete existing entries. -->

# ${slug} — Campaign History

## Campaign Performance

${tableSection}

## Copy Wins

<!-- Agent: append entries as: [ISO date] Campaign: [name] — [what worked and why] -->

(No copy wins recorded yet)

## Copy Losses

<!-- Agent: append entries as: [ISO date] Campaign: [name] — [what failed and why] -->

(No copy losses recorded yet)
`;

  await writeFile(filePath, content, "utf8");
  return { created: true };
}

// ---- feedback.md ------------------------------------------------------------

async function writeFeedback(slug: string, dirPath: string): Promise<{ created: boolean }> {
  const filePath = join(dirPath, "feedback.md");
  if (await fileExists(filePath)) {
    return { created: false };
  }

  const content = `<!-- feedback.md | workspace: ${slug} | seeded: ${isoDate()} | re-seed: skips if exists -->
<!-- Write governance: APPEND only, with ISO timestamp. Max 200 lines. Never delete existing entries. -->

# ${slug} — Client Feedback

## Approval History

<!-- Agent: append entries as: [ISO date] Campaign: [name] — [Approved|Rejected] — [reason if known] -->

(No approval history recorded yet)

## Client Preferences Observed

<!-- Agent: append entries as: [ISO date] — [observed preference, e.g. "prefers shorter sequences", "always asks to remove exclamation marks"] -->

(No preferences observed yet)
`;

  await writeFile(filePath, content, "utf8");
  return { created: true };
}

// ---- learnings.md -----------------------------------------------------------

async function writeLearnings(slug: string, dirPath: string): Promise<{ created: boolean }> {
  const filePath = join(dirPath, "learnings.md");
  if (await fileExists(filePath)) {
    return { created: false };
  }

  const workspace = await prisma.workspace.findUnique({
    where: { slug },
    select: { vertical: true },
  });

  const vertical = or(workspace?.vertical, "Unknown Vertical");

  const content = `<!-- learnings.md | workspace: ${slug} | seeded: ${isoDate()} | re-seed: skips if exists -->
<!-- Write governance: APPEND only, with ISO timestamp. Max 200 lines. Never delete existing entries. -->

# ${slug} — Learnings

## ICP Learnings

<!-- Agent: append entries as: [ISO date] — [what you learned about who responds, e.g. "CTOs at 50-200 person SaaS respond best", "Ignore VP Sales titles for this client"] -->

(No ICP learnings recorded yet)

## Lead Source Effectiveness

<!-- Agent: append entries as: [ISO date] Source: [Apollo|Prospeo|AI Ark|etc] — [quality rating and notes, e.g. "Apollo CTOs at fintech companies 70% valid email rate"] -->

(No lead source data recorded yet)

## ${vertical} — Vertical-Specific Insights

<!-- Agent: append entries as: [ISO date] — [industry pattern, trend, or insight specific to this client's vertical] -->

(No vertical-specific insights recorded yet)
`;

  await writeFile(filePath, content, "utf8");
  return { created: true };
}

// ---- global-insights.md -----------------------------------------------------

async function seedGlobalInsights(): Promise<void> {
  const filePath = join(MEMORY_ROOT, "global-insights.md");

  const allSnapshots = await prisma.cachedMetrics.findMany({
    where: { metricType: "campaign_snapshot" },
    select: { workspace: true, data: true, metricKey: true },
  });

  type ParsedSnapshot = {
    workspace: string;
    replyRate?: number;
    openRate?: number;
    bounceRate?: number;
    totalLeadsContacted?: number;
    channels?: string[];
    status?: string;
  };

  const parsed: ParsedSnapshot[] = [];
  for (const snapshot of allSnapshots) {
    try {
      const d = JSON.parse(snapshot.data as string);
      const total = d.totalLeadsContacted ?? 0;
      const status = d.status ?? "";
      if (total >= 50 && (status === "active" || status === "completed" || status === "paused")) {
        parsed.push({
          workspace: snapshot.workspace,
          replyRate: d.replyRate,
          openRate: d.openRate,
          bounceRate: d.bounceRate,
          totalLeadsContacted: total,
          channels: Array.isArray(d.channels) ? d.channels : ["email"],
          status,
        });
      }
    } catch {
      // skip
    }
  }

  // Compute cross-client email averages
  const emailCampaigns = parsed.filter((p) => !p.channels || p.channels.includes("email"));
  const avgReplyRate = emailCampaigns.length > 0
    ? emailCampaigns.reduce((s, p) => s + (p.replyRate ?? 0), 0) / emailCampaigns.length
    : null;
  const avgOpenRate = emailCampaigns.length > 0
    ? emailCampaigns.reduce((s, p) => s + (p.openRate ?? 0), 0) / emailCampaigns.length
    : null;
  const avgBounceRate = emailCampaigns.length > 0
    ? emailCampaigns.reduce((s, p) => s + (p.bounceRate ?? 0), 0) / emailCampaigns.length
    : null;

  // Group by workspace vertical
  const workspaces = await prisma.workspace.findMany({
    select: { slug: true, vertical: true },
  });
  const verticalMap: Record<string, string> = {};
  for (const ws of workspaces) {
    if (ws.vertical) verticalMap[ws.slug] = ws.vertical;
  }

  // Vertical averages
  const byVertical: Record<string, { count: number; replySum: number; openSum: number }> = {};
  for (const p of emailCampaigns) {
    const vertical = verticalMap[p.workspace] ?? "Unknown";
    if (!byVertical[vertical]) byVertical[vertical] = { count: 0, replySum: 0, openSum: 0 };
    byVertical[vertical].count++;
    byVertical[vertical].replySum += p.replyRate ?? 0;
    byVertical[vertical].openSum += p.openRate ?? 0;
  }

  const verticalRows = Object.entries(byVertical)
    .sort((a, b) => b[1].count - a[1].count)
    .map(([vertical, v]) => {
      const avgReply = ((v.replySum / v.count) * 100).toFixed(1);
      const avgOpen = ((v.openSum / v.count) * 100).toFixed(1);
      return `| ${vertical} | ${v.count} | ${avgReply}% | ${avgOpen}% |`;
    });

  const benchmarksSection = parsed.length > 0
    ? `## Cross-Client Benchmarks

_Based on ${emailCampaigns.length} email campaigns with 50+ leads contacted, across all active workspaces._

| Metric | Value |
|--------|-------|
| Avg Reply Rate (email) | ${avgReplyRate != null ? (avgReplyRate * 100).toFixed(1) + "%" : "No data"} |
| Avg Open Rate (email) | ${avgOpenRate != null ? (avgOpenRate * 100).toFixed(1) + "%" : "No data"} |
| Avg Bounce Rate (email) | ${avgBounceRate != null ? (avgBounceRate * 100).toFixed(1) + "%" : "No data"} |

### By Vertical

| Vertical | Campaigns | Avg Reply Rate | Avg Open Rate |
|----------|-----------|----------------|---------------|
${verticalRows.join("\n") || "| — | — | — | — |"}`
    : `## Cross-Client Benchmarks

_No campaign data with 50+ leads yet. Run campaigns and re-seed to populate benchmarks._`;

  const content = `<!-- global-insights.md | seeded: ${isoDate()} | writer: nova-intel ONLY -->
<!-- Write governance: ONLY nova-intel agent may write here. All other agents: READ ONLY. APPEND with timestamp. Max 200 lines. -->

# Global Insights — Cross-Client Intelligence

${benchmarksSection}

## Best Performing Channels

<!-- nova-intel: append findings as: [ISO date] — [channel] outperforms [other channel] for [vertical] by [X%] reply rate -->

(Populated by nova-intel after campaign data accumulates)

## Copy Patterns

<!-- nova-intel: append patterns as: [ISO date] — [pattern description, e.g. "One-liner strategy outperforms PVP for recruitment vertical by 1.2x"] -->

(Populated by nova-intel after campaign data accumulates)

## Operational Insights

<!-- nova-intel: append insights as: [ISO date] — [operational pattern, e.g. "Tuesday/Wednesday sends get 15% higher open rates", "AI Ark leads show 10% higher reply rate than Apollo for SaaS"] -->

(Populated by nova-intel after campaign data accumulates)
`;

  await writeFile(filePath, content, "utf8");
}

// ---- Per-workspace seed -----------------------------------------------------

async function seedWorkspace(slug: string): Promise<void> {
  const dirPath = join(MEMORY_ROOT, slug);

  await mkdir(dirPath, { recursive: true });
  // Create .gitkeep in slug directory
  await writeFile(join(dirPath, ".gitkeep"), "", "utf8");

  // profile.md — always overwrite
  await writeProfile(slug, dirPath);

  // campaigns.md — skip if exists
  const campaignsResult = await writeCampaigns(slug, dirPath);

  // feedback.md — skip if exists
  const feedbackResult = await writeFeedback(slug, dirPath);

  // learnings.md — skip if exists
  const learningsResult = await writeLearnings(slug, dirPath);

  const profileStatus = "overwritten";
  const campaignsStatus = campaignsResult.created ? "created" : "skipped";
  const feedbackStatus = feedbackResult.created ? "created" : "skipped";
  const learningsStatus = learningsResult.created ? "created" : "skipped";

  console.log(
    `  Seeding ${slug}... profile.md (${profileStatus}), campaigns.md (${campaignsStatus}), feedback.md (${feedbackStatus}), learnings.md (${learningsStatus})`
  );
}

// ---- Main -------------------------------------------------------------------

async function main() {
  const args = process.argv.slice(2);
  const command = args[0];

  if (!command || command === "--help" || command === "-h") {
    console.log(`
Nova Memory CLI — Seed per-workspace memory directories for Nova CLI skills.

Usage:
  npx tsx scripts/nova-memory.ts seed {slug}    Seed one workspace
  npx tsx scripts/nova-memory.ts seed --all     Seed all workspaces from DB

Examples:
  npx tsx scripts/nova-memory.ts seed rise
  npx tsx scripts/nova-memory.ts seed --all
`);
    process.exit(0);
  }

  if (command !== "seed") {
    console.error(`Unknown command: '${command}'. Run with --help for usage.`);
    process.exit(1);
  }

  const target = args[1];
  if (!target) {
    console.error("Usage: nova-memory.ts seed {slug|--all}");
    process.exit(1);
  }

  // Ensure memory root + root .gitkeep exist
  await mkdir(MEMORY_ROOT, { recursive: true });
  const rootGitkeep = join(MEMORY_ROOT, ".gitkeep");
  if (!(await fileExists(rootGitkeep))) {
    await writeFile(rootGitkeep, "", "utf8");
  }

  if (target === "--all") {
    const workspaces = await prisma.workspace.findMany({
      select: { slug: true },
      orderBy: { slug: "asc" },
    });

    console.log(`Seeding ${workspaces.length} workspaces...\n`);
    for (const ws of workspaces) {
      await seedWorkspace(ws.slug);
    }

    console.log("\nSeeding global insights...");
    await seedGlobalInsights();
    console.log("  global-insights.md (overwritten)");

    console.log(`\nDone. Memory seeded at ${MEMORY_ROOT}/`);
  } else {
    // Single workspace
    await seedWorkspace(target);

    console.log("\nSeeding global insights...");
    await seedGlobalInsights();
    console.log("  global-insights.md (overwritten)");

    console.log(`\nDone. Memory seeded at ${MEMORY_ROOT}/${target}/`);
  }

  await prisma.$disconnect();
}

main().catch((err) => {
  console.error("Error:", err.message);
  prisma.$disconnect();
  process.exit(1);
});
