export const EMAILBISON_CUSTOM_VARIABLE_NAMES = [
  "LOCATION",
  "LASTEMAILMONTH",
  "OOO_GREETING",
] as const;

export const EMAILBISON_CUSTOM_VARIABLE_NAME_SET: ReadonlySet<string> =
  new Set(EMAILBISON_CUSTOM_VARIABLE_NAMES);

export const EMAILBISON_STANDARD_SEQUENCE_CUSTOM_VARIABLES = [
  "LOCATION",
  "LASTEMAILMONTH",
] as const;
