import { beforeEach, describe, expect, it, vi } from "vitest";

const { mockSend, mockRenderToBuffer, mockAudited, mockAuditSkipped } = vi.hoisted(() => ({
  mockSend: vi.fn(),
  mockRenderToBuffer: vi.fn().mockResolvedValue(Buffer.from("pdf")),
  mockAudited: vi.fn(async (_entry, sendFn) => sendFn()),
  mockAuditSkipped: vi.fn(),
}));

vi.mock("resend", () => ({
  Resend: class {
    emails = { send: mockSend };
  },
}));

vi.mock("@react-pdf/renderer", () => ({
  renderToBuffer: mockRenderToBuffer,
}));

vi.mock("@/lib/invoices/pdf", () => ({
  InvoicePdfDocument: () => null,
}));

vi.mock("@/lib/notification-audit", () => ({
  audited: mockAudited,
  auditSkipped: mockAuditSkipped,
}));

const invoice = {
  id: "inv-1",
  invoiceNumber: "INV-001",
  workspaceSlug: "acme",
  senderName: "Outsignal",
  senderAddress: null,
  senderEmail: "billing@outsignal.ai",
  bankDetails: null,
  clientCompanyName: "Acme",
  clientAddress: null,
  issueDate: new Date("2026-04-01T00:00:00.000Z"),
  dueDate: new Date("2026-04-08T00:00:00.000Z"),
  billingPeriodStart: null,
  billingPeriodEnd: null,
  subtotalPence: 1000,
  taxRate: 0,
  taxAmountPence: 0,
  totalPence: 1000,
  status: "draft",
  sentAt: null,
  paidAt: null,
  autoGenerated: false,
  renewalDate: null,
  viewToken: "token-1",
  reminderSentAt: null,
  createdAt: new Date("2026-04-01T00:00:00.000Z"),
  updatedAt: new Date("2026-04-01T00:00:00.000Z"),
  lineItems: [],
};

describe("sendInvoiceEmail", () => {
  const originalEnv = { ...process.env };

  beforeEach(() => {
    vi.clearAllMocks();
    process.env = { ...originalEnv };
    delete process.env.RESEND_API_KEY;
    delete process.env.RESEND_FROM;
  });

  it("returns a skipped result when RESEND_API_KEY is not configured", async () => {
    const { sendInvoiceEmail } = await import("@/lib/invoices/email");

    const result = await sendInvoiceEmail(invoice, "client@example.com");

    expect(result).toEqual({
      delivered: false,
      providerId: null,
      reason: "resend_not_configured",
    });
    expect(mockAuditSkipped).toHaveBeenCalled();
    expect(mockSend).not.toHaveBeenCalled();
  });

  it("returns delivered=true and providerId when Resend accepts the send", async () => {
    process.env.RESEND_API_KEY = "re_test_123";
    mockSend.mockResolvedValue({ data: { id: "email-123" } });

    const { sendInvoiceEmail } = await import("@/lib/invoices/email");

    const result = await sendInvoiceEmail(invoice, "client@example.com");

    expect(result).toEqual({
      delivered: true,
      providerId: "email-123",
    });
  });
});
