import { beforeEach, describe, expect, it, vi } from "vitest";

const findManyMock = vi.fn();
const updateMock = vi.fn();
const findFirstMock = vi.fn();
const createInvoiceMock = vi.fn();

vi.mock("@/lib/db", () => ({
  prisma: {
    workspace: {
      findMany: findManyMock,
      update: updateMock,
    },
    invoice: {
      findFirst: findFirstMock,
    },
  },
}));

vi.mock("@/lib/notify", () => ({
  notify: vi.fn().mockResolvedValue(undefined),
}));

vi.mock("@/lib/invoices/operations", () => ({
  createInvoice: createInvoiceMock,
}));

describe("generateDueInvoices", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("creates due invoices without advancing workspace billingRenewalDate", async () => {
    const renewalDate = new Date("2026-04-30T00:00:00.000Z");
    findManyMock.mockResolvedValue([
      {
        slug: "acme",
        billingRenewalDate: renewalDate,
        billingRetainerPence: 100000,
        billingPlatformFeePence: 25000,
      },
    ]);
    findFirstMock.mockResolvedValue(null);
    createInvoiceMock.mockResolvedValue({ id: "inv-1" });

    const { generateDueInvoices } = await import("@/lib/invoices/generator");
    const result = await generateDueInvoices();

    expect(result).toEqual({ created: 1, skipped: 0 });
    expect(createInvoiceMock).toHaveBeenCalledWith(
      expect.objectContaining({
        workspaceSlug: "acme",
        renewalDate,
        autoGenerated: true,
      }),
    );
    expect(updateMock).not.toHaveBeenCalled();
  });
});
