export type StageKey = "onboarding" | "campaign_setup" | "campaign_launch" | "customer_success";
export type TemplateType = "email" | "email_linkedin" | "linkedin" | "consultancy";

export interface SubtaskTemplate {
  title: string;
  order: number;
}

export interface TaskTemplate {
  stage: StageKey;
  title: string;
  order: number;
  assignee: string;
  subtasks: SubtaskTemplate[];
  /** Index references to other tasks in the same template that block this one */
  blockedByIndices?: number[];
  /** Days from client start date when this task is due */
  dueDaysFromStart?: number;
  /** Recurring schedule: null = one-shot, "weekly" | "monthly" */
  recurring?: string;
  /** Day of week (0=Sun, 5=Fri) for weekly, day of month (1-31, -1=last working day) for monthly */
  recurringDay?: number;
}

export const STAGES = [
  { value: "onboarding" as const, label: "Onboarding" },
  { value: "campaign_setup" as const, label: "Campaign Setup" },
  { value: "campaign_launch" as const, label: "Campaign Launch" },
  { value: "customer_success" as const, label: "Customer Success" },
] as const;

export const PIPELINE_STATUSES = [
  { value: "new_lead", label: "New Lead", color: "#87909e" },
  { value: "contacted", label: "Contacted", color: "#5f55ee" },
  { value: "qualified", label: "Qualified Prospect", color: "#6366f1" },
  { value: "demo", label: "Demo", color: "#8b5cf6" },
  { value: "proposal", label: "Proposal", color: "#f59e0b" },
  { value: "negotiation", label: "Negotiation", color: "#f97316" },
  { value: "closed_won", label: "Closed Won", color: "#22c55e" },
  { value: "closed_lost", label: "Closed Lost", color: "#ef4444" },
  { value: "unqualified", label: "Unqualified", color: "#64748b" },
  { value: "churned", label: "Churned", color: "#e11d48" },
] as const;

export const CAMPAIGN_TYPES = [
  { value: "email" as const, label: "Email Only" },
  { value: "email_linkedin" as const, label: "Email + LinkedIn" },
  { value: "linkedin" as const, label: "LinkedIn" },
  { value: "consultancy" as const, label: "Consultancy" },
] as const;

export const TASK_TEMPLATES: Record<TemplateType, TaskTemplate[]> = {
  email: [
    {
      stage: "onboarding",
      title: "Receive signed proposal + onboarding doc",
      order: 0,
      assignee: "client",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Raise first invoice",
      order: 1,
      assignee: "pm",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Create Outsignal workspace",
      order: 2,
      assignee: "pm",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Upload exclusion list",
      order: 3,
      assignee: "nova",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Create Slack channel",
      order: 4,
      assignee: "pm",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Invite to portal",
      order: 5,
      assignee: "pm",
      dueDaysFromStart: 2,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Purchase sending domains",
      order: 6,
      assignee: "pm",
      dueDaysFromStart: 2,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Order inboxes",
      order: 7,
      assignee: "pm",
      dueDaysFromStart: 2,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "DNS setup + verification",
      order: 8,
      assignee: "monty",
      dueDaysFromStart: 3,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Warmup started + monitor",
      order: 9,
      assignee: "monty",
      dueDaysFromStart: 4,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Store SOW + T&Cs",
      order: 10,
      assignee: "pm",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Website research + ICP extraction",
      order: 11,
      assignee: "nova",
      dueDaysFromStart: 3,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Client profile doc + KB ingestion",
      order: 12,
      assignee: "nova",
      dueDaysFromStart: 3,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Onboarding complete",
      order: 13,
      assignee: "pm",
      dueDaysFromStart: 5,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Confirm warmup complete",
      order: 14,
      assignee: "monty",
      dueDaysFromStart: 21,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Discovery — source leads",
      order: 15,
      assignee: "nova",
      dueDaysFromStart: 6,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Enrichment + verification",
      order: 16,
      assignee: "nova",
      dueDaysFromStart: 7,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Write email sequences",
      order: 17,
      assignee: "nova",
      dueDaysFromStart: 8,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Publish campaigns for approval",
      order: 18,
      assignee: "nova",
      dueDaysFromStart: 9,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Client approves in portal",
      order: 19,
      assignee: "client",
      dueDaysFromStart: 10,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Pre-launch deliverability check",
      order: 20,
      assignee: "nova",
      dueDaysFromStart: 10,
      subtasks: [],
    },
    {
      stage: "campaign_launch",
      title: "Deploy approved campaigns",
      order: 21,
      assignee: "pm",
      dueDaysFromStart: 11,
      subtasks: [],
    },
    {
      stage: "campaign_launch",
      title: "Send launch confirmation",
      order: 22,
      assignee: "pm",
      dueDaysFromStart: 11,
      subtasks: [],
    },
    {
      stage: "campaign_launch",
      title: "Post-launch verification (24hr)",
      order: 23,
      assignee: "monty",
      dueDaysFromStart: 12,
      subtasks: [],
    },
    {
      stage: "campaign_launch",
      title: "2-week performance report",
      order: 24,
      assignee: "nova",
      dueDaysFromStart: 25,
      subtasks: [],
    },
    {
      stage: "customer_success",
      title: "Send Weekly Campaign + Lead Report [FRIDAY]",
      order: 25,
      assignee: "pm",
      dueDaysFromStart: 18,
      recurring: "weekly",
      recurringDay: 5,
      subtasks: [],
    },
    {
      stage: "customer_success",
      title: "Send Monthly Campaign + Lead Report [LAST WORKING DAY]",
      order: 26,
      assignee: "pm",
      dueDaysFromStart: 30,
      recurring: "monthly",
      recurringDay: -1,
      subtasks: [],
    },
    {
      stage: "customer_success",
      title: "Monthly Content Review",
      order: 27,
      assignee: "pm",
      dueDaysFromStart: 30,
      recurring: "monthly",
      recurringDay: -1,
      subtasks: [],
    },
  ],
  email_linkedin: [
    {
      stage: "onboarding",
      title: "Receive signed proposal + onboarding doc",
      order: 0,
      assignee: "client",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Raise first invoice",
      order: 1,
      assignee: "pm",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Create Outsignal workspace",
      order: 2,
      assignee: "pm",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Upload exclusion list",
      order: 3,
      assignee: "nova",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Create Slack channel",
      order: 4,
      assignee: "pm",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Invite to portal",
      order: 5,
      assignee: "pm",
      dueDaysFromStart: 2,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Purchase sending domains",
      order: 6,
      assignee: "pm",
      dueDaysFromStart: 2,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Order inboxes",
      order: 7,
      assignee: "pm",
      dueDaysFromStart: 2,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "DNS setup + verification",
      order: 8,
      assignee: "monty",
      dueDaysFromStart: 3,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Warmup started + monitor",
      order: 9,
      assignee: "monty",
      dueDaysFromStart: 4,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "LinkedIn account connected",
      order: 10,
      assignee: "client",
      dueDaysFromStart: 3,
      subtasks: [
        { title: "Client signs into platform", order: 0 },
        { title: "Verify account connected", order: 1 },
        { title: "Check warmup required", order: 2 },
      ],
    },
    {
      stage: "onboarding",
      title: "Store SOW + T&Cs",
      order: 11,
      assignee: "pm",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Website research + ICP extraction",
      order: 12,
      assignee: "nova",
      dueDaysFromStart: 3,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Client profile doc + KB ingestion",
      order: 13,
      assignee: "nova",
      dueDaysFromStart: 3,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Onboarding complete",
      order: 14,
      assignee: "pm",
      dueDaysFromStart: 5,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Confirm warmup complete",
      order: 15,
      assignee: "monty",
      dueDaysFromStart: 21,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Discovery — source leads",
      order: 16,
      assignee: "nova",
      dueDaysFromStart: 6,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Enrichment + verification",
      order: 17,
      assignee: "nova",
      dueDaysFromStart: 7,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Write email sequences",
      order: 18,
      assignee: "nova",
      dueDaysFromStart: 8,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Write LinkedIn sequences",
      order: 19,
      assignee: "nova",
      dueDaysFromStart: 8,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Publish campaigns for approval",
      order: 20,
      assignee: "nova",
      dueDaysFromStart: 9,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Client approves in portal",
      order: 21,
      assignee: "client",
      dueDaysFromStart: 10,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Pre-launch deliverability check",
      order: 22,
      assignee: "nova",
      dueDaysFromStart: 10,
      subtasks: [],
    },
    {
      stage: "campaign_launch",
      title: "Deploy approved campaigns",
      order: 23,
      assignee: "pm",
      dueDaysFromStart: 11,
      subtasks: [],
    },
    {
      stage: "campaign_launch",
      title: "Send launch confirmation",
      order: 24,
      assignee: "pm",
      dueDaysFromStart: 11,
      subtasks: [],
    },
    {
      stage: "campaign_launch",
      title: "Post-launch verification (24hr)",
      order: 25,
      assignee: "monty",
      dueDaysFromStart: 12,
      subtasks: [],
    },
    {
      stage: "campaign_launch",
      title: "2-week performance report",
      order: 26,
      assignee: "nova",
      dueDaysFromStart: 25,
      subtasks: [],
    },
    {
      stage: "customer_success",
      title: "Send Weekly Campaign + Lead Report [FRIDAY]",
      order: 27,
      assignee: "pm",
      dueDaysFromStart: 18,
      recurring: "weekly",
      recurringDay: 5,
      subtasks: [],
    },
    {
      stage: "customer_success",
      title: "Send Monthly Campaign + Lead Report [LAST WORKING DAY]",
      order: 28,
      assignee: "pm",
      dueDaysFromStart: 30,
      recurring: "monthly",
      recurringDay: -1,
      subtasks: [],
    },
    {
      stage: "customer_success",
      title: "Monthly Content Review",
      order: 29,
      assignee: "pm",
      dueDaysFromStart: 30,
      recurring: "monthly",
      recurringDay: -1,
      subtasks: [],
    },
  ],
  linkedin: [
    {
      stage: "onboarding",
      title: "Receive signed proposal + onboarding doc",
      order: 0,
      assignee: "client",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Raise first invoice",
      order: 1,
      assignee: "pm",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Create Outsignal workspace",
      order: 2,
      assignee: "pm",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Upload exclusion list",
      order: 3,
      assignee: "nova",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Create Slack channel",
      order: 4,
      assignee: "pm",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Invite to portal",
      order: 5,
      assignee: "pm",
      dueDaysFromStart: 2,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "LinkedIn account connected",
      order: 6,
      assignee: "client",
      dueDaysFromStart: 3,
      subtasks: [
        { title: "Client signs into platform", order: 0 },
        { title: "Verify account connected", order: 1 },
        { title: "Check warmup required", order: 2 },
      ],
    },
    {
      stage: "onboarding",
      title: "Store SOW + T&Cs",
      order: 7,
      assignee: "pm",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Website research + ICP extraction",
      order: 8,
      assignee: "nova",
      dueDaysFromStart: 3,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Client profile doc + KB ingestion",
      order: 9,
      assignee: "nova",
      dueDaysFromStart: 3,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Onboarding complete",
      order: 10,
      assignee: "pm",
      dueDaysFromStart: 5,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Discovery — source leads",
      order: 11,
      assignee: "nova",
      dueDaysFromStart: 6,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Enrichment + verification",
      order: 12,
      assignee: "nova",
      dueDaysFromStart: 7,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Write LinkedIn sequences",
      order: 13,
      assignee: "nova",
      dueDaysFromStart: 8,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Publish campaigns for approval",
      order: 14,
      assignee: "nova",
      dueDaysFromStart: 9,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Client approves in portal",
      order: 15,
      assignee: "client",
      dueDaysFromStart: 10,
      subtasks: [],
    },
    {
      stage: "campaign_launch",
      title: "Deploy approved campaigns",
      order: 16,
      assignee: "pm",
      dueDaysFromStart: 11,
      subtasks: [],
    },
    {
      stage: "campaign_launch",
      title: "Post-launch verification (24hr)",
      order: 17,
      assignee: "monty",
      dueDaysFromStart: 12,
      subtasks: [],
    },
    {
      stage: "campaign_launch",
      title: "2-week performance report",
      order: 18,
      assignee: "nova",
      dueDaysFromStart: 25,
      subtasks: [],
    },
    {
      stage: "customer_success",
      title: "Send Weekly Campaign + Lead Report [FRIDAY]",
      order: 19,
      assignee: "pm",
      dueDaysFromStart: 18,
      recurring: "weekly",
      recurringDay: 5,
      subtasks: [],
    },
    {
      stage: "customer_success",
      title: "Send Monthly Campaign + Lead Report [LAST WORKING DAY]",
      order: 20,
      assignee: "pm",
      dueDaysFromStart: 30,
      recurring: "monthly",
      recurringDay: -1,
      subtasks: [],
    },
    {
      stage: "customer_success",
      title: "Monthly Content Review",
      order: 21,
      assignee: "pm",
      dueDaysFromStart: 30,
      recurring: "monthly",
      recurringDay: -1,
      subtasks: [],
    },
  ],
  consultancy: [
    {
      stage: "onboarding",
      title: "Receive signed proposal + onboarding doc",
      order: 0,
      assignee: "client",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Raise first invoice",
      order: 1,
      assignee: "pm",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Create Outsignal workspace",
      order: 2,
      assignee: "pm",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Create Slack channel + invite",
      order: 3,
      assignee: "pm",
      dueDaysFromStart: 1,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Invite to portal",
      order: 4,
      assignee: "pm",
      dueDaysFromStart: 2,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Audit existing infrastructure",
      order: 5,
      assignee: "pm",
      dueDaysFromStart: 3,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Website research + ICP extraction",
      order: 6,
      assignee: "nova",
      dueDaysFromStart: 3,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Client profile doc + KB ingestion",
      order: 7,
      assignee: "nova",
      dueDaysFromStart: 3,
      subtasks: [],
    },
    {
      stage: "onboarding",
      title: "Onboarding complete",
      order: 8,
      assignee: "pm",
      dueDaysFromStart: 5,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Review client's existing campaigns",
      order: 9,
      assignee: "pm",
      dueDaysFromStart: 6,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Provide ICP + targeting recommendations",
      order: 10,
      assignee: "nova",
      dueDaysFromStart: 7,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Review client's copy + provide feedback",
      order: 11,
      assignee: "nova",
      dueDaysFromStart: 8,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Deliverability audit",
      order: 12,
      assignee: "nova",
      dueDaysFromStart: 9,
      subtasks: [],
    },
    {
      stage: "campaign_setup",
      title: "Strategy call with client",
      order: 13,
      assignee: "pm",
      dueDaysFromStart: 10,
      subtasks: [],
    },
    {
      stage: "customer_success",
      title: "Send Weekly Campaign + Lead Report [FRIDAY]",
      order: 14,
      assignee: "pm",
      dueDaysFromStart: 18,
      recurring: "weekly",
      recurringDay: 5,
      subtasks: [],
    },
    {
      stage: "customer_success",
      title: "Send Monthly Campaign + Lead Report [LAST WORKING DAY]",
      order: 15,
      assignee: "pm",
      dueDaysFromStart: 30,
      recurring: "monthly",
      recurringDay: -1,
      subtasks: [],
    },
    {
      stage: "customer_success",
      title: "Monthly Content Review",
      order: 16,
      assignee: "pm",
      dueDaysFromStart: 30,
      recurring: "monthly",
      recurringDay: -1,
      subtasks: [],
    },
  ],
};
